baseURL = "https://tszlau.com"
title = "tszlau"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "<div id='logo-col'><img src='img/small_logo.png' alt='tszlau logo' id='small-logo' /><br />tszlau</div>"
copyright = "Samuel Thompson"
description = 'Website Design<br />Application Development<br />Consultation & Solution Development<br />Data ETL Pipelines and Policies<br />Web Education & Tutoring'
startbuttonText = "Schedule A Consultation Today"
# update link to href of contact form
startbuttonLink = "#contact"
body_is_markdown = true
# custom_css = "custom.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

# [[params.menu.main]]
# url = '/'
# title = "Home"

# [[params.menu.main]]
# url = '/posts/'
# title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = "Experienced Web & Application Developers... Let's build something great"
body = '''
Have an existing framework, great! No? Let's develop one together from the ground up. Whatever your business needs are, we'll create sustainable (long-lasting), and cost effective solutions to meet the unique demands of your business.
'''

[[params.one.icon]]
icon = "solid fa-mobile"
style = "1"
label = "Mobile"

[[params.one.icon]]
icon = "solid fa-database"
style = "2"
label = "Browser"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Development"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = "Data Issues No More"
body = "Years of experience not only developing data ingestion tools, but building and maintaining Extract / Load / Transform (ETL) pipelines so you know what's happening in your business and why."

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Not Technical...No Sweat!'
body = "With experience working within a plethora of industries, we're able to communicate effectively with technical and non-technical stakeholders to ensure that stakeholders are stastified with results."

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Sustainable & Scalable Solutions'
body = "Let's work together to develop something that is not only solves the business problems of today, but will be able to grow with and meet the needs of your business in the future."

[params.three]
enable = true
title = 'Services We Offer'
body = '''
A small sampling of services and products available through tszlau
'''

[[params.three.feature]]
icon = "solid fa-handshake"
title = "Consultations"
body = "Evaluation of current business loads and processes, while identifying areas for improvement. Generate results, reports, and policies that can be read by technical and non-technical stakeholders alike."

[[params.three.feature]]
icon = "solid fa-pen-nib"
title = "Web Design"
body = "Creation of a unique and beautiful website that accurately portrays and invites customers to your business."

[[params.three.feature]]
icon = "brands fa-app-store-ios"
title = "Application Development"
body = "Mobile or Desktop needs not being met? Let's develop a custom solution to meet your needs."

[[params.three.feature]]
icon = "solid fa-database"
title = "Data Pipelines & Policy"
body = "Use of Extract / Transform / Load pipelines to aggregate data from a variety of sources and give you insights, and provide a holistic picture of the health of your business in real time."

[[params.three.feature]]
icon = "solid fa-hashtag"
title = "Social Media Management"
body = "Need a content media platform that manage and schedule posts all while ensuring brand consistency across mutltiple channels? We've got you covered."

[[params.three.feature]]
icon = "solid fa-dna"
title = "Custom Solutions"
body = "Need something that isn't on this list? Let's work together to come up with a solution that's unique, just like the needs of your business."

[params.contact]
enable = true
title = "Contact"
body = "Schedule a consultation or drop us a line describing how we can help you achieve your business goals today."
phone = "+1 (216) 970 1203"
address = "Cleveland Heights, OH<br />USA"
email = "thomps9012.webdev@gmail.com"
subject = "New Submission!"
formspree_form_id = "xyyqgvrn"

[params.social]
twitter = "@tszlau_0"
github = ""
facebook = "profile.php?id=100063777284540"
youtube = ""
instagram = "tszlau_0"

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
