baseURL = "https://tszlau.com"
title = "tszlau"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "<div id='logo-col'><img src='img/small_logo.png' alt='tszlau logo' id='small-logo' /><br />tszlau</div>"
copyright = "Samuel Thompson"
description = 'Software Consulting'
description2 = 'Web / Application Design & Development'
description3 = 'Custom Software Solutions'
description4 = 'Data Pipelines & Policy'
startbuttonText = "Get in Touch Today"
startbuttonLink = "#contact"
body_is_markdown = true

# [[params.menu.main]]
# url = '/'
# title = "Home"

# [[params.menu.main]]
# url = '/posts/'
# title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = "Let's build something great"
body = '''
Have an existing product or framework that needs to be updated or built upon, great! New idea? We'll develop a custom solution together from the ground up. Whatever your business needs, we'll create long-lasting, cost effective solutions to meet the unique demands of your business.
'''

[[params.one.icon]]
icon = "solid fa-mobile"
style = "1"
label = "Mobile"

[[params.one.icon]]
icon = "solid fa-database"
style = "2"
label = "Browser"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Development"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Not Technical...No Sweat!'
body = "We're able to communicate effectively with technical and non-technical stakeholders alike to ensure that everyone's stastified."

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Sustainable & Scalable Solutions'
body = "We'll help you build a solutions that not only solves the problems of today, but will be able to grow with your business to meet the demands of tomorrow."

[params.three]
enable = true
title = 'Services We Offer'
body = '''
A small sampling of services and products available at tszlau
'''

[[params.three.feature]]
icon = "solid fa-handshake"
title = "Software Consulting"
body = "Evaluate either current or new digital solutions. Create cohesive and comprehensive solutions with debriefs / reports that can be understood by technical and non-technical stakeholders alike."

[[params.three.feature]]
icon = "solid fa-pen-nib"
title = "Web / Application Design"
body = "Creation of unique and beautiful AI, applications, and websites that accurately meet your business needs, and leave a lasting impression."

[[params.three.feature]]
icon = "solid fa-database"
title = "Data Pipelines & Policy"
body = "Extract / Transform / Load pipelines that aggregate data in realtime from a variety of sources and provide a holistic picture of the health of your business."

[[params.three.feature]]
icon = "solid fa-dna"
title = "Custom Solutions"
body = "Need something that isn't on this list? Let's put our heads together to come up with something unique and amazing, just like your business."

[params.contact]
enable = true
title = "Contact"
body = "Schedule a meeting or drop us a line describing how we can help you achieve your goals today."
phone = "+1 (216) 970 1203"
address = "Cleveland Heights, OH<br />USA"
email = "thomps9012.webdev@gmail.com"
subject = "New Submission!"
formspree_form_id = "xyyqgvrn"

[params.social]
twitter = ""
github = "thomps9012"
linkedin = "samuel-joseph-thompson"
youtube = ""
instagram = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
